#!/bin/bash

dmd -ofphase3 src/main.d -Isrc/dwt/imp -Jsrc/dwt/org.eclipse.swt.gtk.linux.x86/res -L-Lsrc/dwt/lib \
-L-l:org.eclipse.swt.gtk.linux.x86 \
-L-l:dwt-base -L-lgtk-x11-2.0 -L-lgdk-x11-2.0 -L-latk-1.0 -L-lgdk_pixbuf-2.0 \
-L-lgthread-2.0 -L-lpangocairo-1.0 -L-lfontconfig -L-lXtst -L-lXext -L-lXrender \
-L-lXinerama -L-lXi -L-lXrandr -L-lXcursor -L-lXcomposite -L-lXdamage -L-lX11 \
-L-lXfixes -L-lpango-1.0 -L-lgobject-2.0 -L-lgmodule-2.0 -L-ldl -L-lglib-2.0 \
-L-lcairo -L-lgnomeui-2
